import { describe, expect, it } from "vitest";

import { normalizeTrustedSvgAsset } from "./normalize-svg";

describe("normalizeTrustedSvgAsset", () => {
  it("should strip document wrappers and normalize root attributes when an SVG is prepared for nesting", () => {
    // Given
    const sourceSvg = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg [
  <!ENTITY example "ignored">
]>
<!-- generated by an editor -->
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="64" x="4" y="8" viewBox="0 0 32 16">
  <!-- source comment -->
  <path id="mark" fill="url(#paint)" d="M0 0h32v16H0z"/>
  <defs><linearGradient id="paint"><stop stop-color="#000"/></linearGradient></defs>
</svg>`;

    // When
    const normalizedSvg = normalizeTrustedSvgAsset({
      occurrence: 2,
      slug: "typescript",
      sourceSvg,
    });

    // Then
    expect(normalizedSvg.viewBox).toBe("0 0 32 16");
    expect(normalizedSvg.attributes).toBe(
      'xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 16" preserveAspectRatio="xMidYMid meet"',
    );
    expect(normalizedSvg.attributes).not.toMatch(/\bwidth=/);
    expect(normalizedSvg.attributes).not.toMatch(/\bheight=/);
    expect(normalizedSvg.attributes).not.toMatch(/\sx=/);
    expect(normalizedSvg.attributes).not.toMatch(/\sy=/);
    expect(normalizedSvg.body).not.toContain("<?xml");
    expect(normalizedSvg.body).not.toContain("<!DOCTYPE");
    expect(normalizedSvg.body).not.toContain("<!--");
    expect(normalizedSvg.body).toContain('id="icon-typescript-2-mark"');
    expect(normalizedSvg.body).toContain("url(#icon-typescript-2-paint)");
  });

  it("should derive a viewBox when numeric dimensions are available", () => {
    // Given
    const sourceSvg = `<svg width="24px" height="12" preserveAspectRatio="none">
  <path d="M0 0h24v12H0z"/>
</svg>`;

    // When
    const normalizedSvg = normalizeTrustedSvgAsset({
      occurrence: 0,
      slug: "react",
      sourceSvg,
    });

    // Then
    expect(normalizedSvg.viewBox).toBe("0 0 24 12");
    expect(normalizedSvg.attributes).toBe(
      'viewBox="0 0 24 12" preserveAspectRatio="none"',
    );
  });

  it("should extract the root SVG reliably when nested SVG attributes contain angle brackets", () => {
    // Given
    const sourceSvg = `<svg width="40" height="40">
  <svg viewBox="0 0 10 10" data-label="1 > 0"><path d="M0 0h10v10H0z"/></svg>
</svg>`;

    // When
    const normalizedSvg = normalizeTrustedSvgAsset({
      occurrence: 1,
      slug: "nextjs",
      sourceSvg,
    });

    // Then
    expect(normalizedSvg.viewBox).toBe("0 0 40 40");
    expect(normalizedSvg.body).toBe(
      '<svg viewBox="0 0 10 10" data-label="1 > 0"><path d="M0 0h10v10H0z"/></svg>',
    );
  });

  it("should reject SVGs when neither viewBox nor numeric dimensions are available", () => {
    // Given
    const sourceSvg = `<svg width="2rem" height="auto"><path d="M0 0h1v1H0z"/></svg>`;

    // When
    const normalize = () =>
      normalizeTrustedSvgAsset({
        occurrence: 0,
        slug: "vercel",
        sourceSvg,
      });

    // Then
    expect(normalize).toThrow(
      "Icon asset must include a viewBox or numeric width and height.",
    );
  });
});
